/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;
import clases.Persona;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author yescobar7
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    ArrayList<Persona> v= new ArrayList();
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdentifiacion = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        cdmGuardar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdListarMujeres = new javax.swing.JButton();
        cmdCantMujeres = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Personas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Basicos", 0, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Identificacion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Primer Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Primer Apellido");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel2.add(txtIdentifiacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 260, -1));
        jPanel2.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 260, -1));
        jPanel2.add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Genero");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino", "Indefinido", " " }));
        cmbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGeneroActionPerformed(evt);
            }
        });
        jPanel2.add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 170));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", 0, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cdmGuardar.setBackground(new java.awt.Color(255, 255, 255));
        cdmGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cdmGuardar.setText("GUARDAR");
        cdmGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(cdmGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, -1));

        cmdMostrar.setBackground(new java.awt.Color(255, 255, 255));
        cmdMostrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdMostrar.setText("MOSTRAR");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, -1));

        cmdLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        cmdLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdLimpiar.setText("LIMPIAR");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, -1));

        cmdListarMujeres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdListarMujeres.setText("LISTAR MUJ");
        cmdListarMujeres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdListarMujeresActionPerformed(evt);
            }
        });
        jPanel4.add(cmdListarMujeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        cmdCantMujeres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdCantMujeres.setText("CANTIDAD DE MUJERES");
        cmdCantMujeres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCantMujeresActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCantMujeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 210, 230));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", 0, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 31, 520, 190));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 550, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(690, 604));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cdmGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmGuardarActionPerformed
    Persona p;
    long identificacion;
    String primer_nombre;
    String primer_apellido;
    String Genero;
    identificacion = Long.parseLong(txtIdentifiacion.getText());
    primer_nombre= txtPrimerNombre.getText();
    primer_apellido= txtPrimerApellido.getText();
    Genero= cmbGenero.getSelectedItem().toString();
    
    p = new Persona(identificacion, primer_nombre, primer_apellido, Genero);
    v.add(p);
    JOptionPane.showMessageDialog(this, "persona agregada exitosamente!");
    txtIdentifiacion.setText("");
    txtPrimerNombre.setText("");
    txtPrimerApellido.setText("");
    txtIdentifiacion.requestFocusInWindow();
    cmbGenero.setSelectedItem(0);
    
    
    
    }//GEN-LAST:event_cdmGuardarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
    String aux;
    txtResultado.setText("");
    if(v.isEmpty()){
    txtResultado.setText("no hay personas que mostrar");
    }
    else{
    for (int i = 0; i < v.size(); i++) {
    aux= "Persona No. "+(i)+"\n"
         + "Identificacicon: "+v.get(i).getIdentificacion()+"\n"
         + "primer nombre: "+v.get(i).getPrimer_nombre()+"\n"
         + "primer apellido: "+v.get(i).getPrimer_apellido()+"\n"
         + "Genero: "+v.get(i).getGenero()+"\n\n";
        
    txtResultado.append(aux);    
    }
    }
    txtIdentifiacion.requestFocusInWindow();
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
    int op;
    op = JOptionPane.showConfirmDialog(this, "¿seguro que desea eliminar las peronas", "Pregunta", JOptionPane.YES_NO_OPTION);
    if(op== JOptionPane.YES_OPTION){
    v.clear();
    txtResultado.setText("");
    txtIdentifiacion.setText("");
    txtPrimerNombre.setText("");
    txtPrimerApellido.setText("");
    txtIdentifiacion.requestFocusInWindow();
    }
    
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGeneroActionPerformed

    private void cmdListarMujeresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListarMujeresActionPerformed
    String aux;  
    int cont=0;
    txtResultado.setText("");
    if(v.isEmpty()){
    txtResultado.setText("no hay personas que mostrar");
    }
    else{
    for (int i = 0; i < v.size(); i++) {
    if(v.get(i).getGenero().equalsIgnoreCase("Femenino")){
    aux= "Persona No. "+(i)+"\n"
         + "Identificacicon: "+v.get(i).getIdentificacion()+"\n"
         + "primer nombre: "+v.get(i).getPrimer_nombre()+"\n"
         + "primer apellido: "+v.get(i).getPrimer_apellido()+"\n"
         + "Genero: "+v.get(i).getGenero()+"\n\n";
        
    txtResultado.append(aux); 
    cont++;
    }
    }
    if(cont==0){
    txtResultado.setText("No Hay Mujeres Que Mostrar");
    }
    }
    txtIdentifiacion.requestFocusInWindow();
    }//GEN-LAST:event_cmdListarMujeresActionPerformed

    private void cmdCantMujeresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCantMujeresActionPerformed
    int cont=0;
    for (int i = 0; i < v.size(); i++) {
    if(v.get(i).getGenero().equalsIgnoreCase("Femenino")){
    cont++;
    }
    txtResultado.setText("El numero de mujeres es: "+cont);
    }
    }//GEN-LAST:event_cmdCantMujeresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdmGuardar;
    private javax.swing.JComboBox cmbGenero;
    private javax.swing.JButton cmdCantMujeres;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdListarMujeres;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdentifiacion;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
